#SQL Connection
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emaildb
    name: email_sys
    username: root
    password: ENC(50sp6H9n/6nEhb0NxVXHCe593KfrmSok)
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
#Password Encryption
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: projectPassword
#Server
server:
  error:
    whitelabel:
      enabled: false
  port: 8000
---
#Spring Kafka
spring:
  kafka:
    template:
      default-topic: userdata-topic
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: user-group
      properties:
        spring.json.trusted.packages: "*"